"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var authController_1 = require("../controllers/authController");
var auth_1 = require("../middleware/auth");
var router = (0, express_1.Router)();
router.post("/signup", authController_1.signup);
router.post("/login", authController_1.login);
router.post("/refresh", authController_1.refresh);
router.get("/verify-email/:token", authController_1.verifyEmail);
router.post("/forgot-password", authController_1.forgotPassword);
router.post("/reset-password", authController_1.resetPassword);
router.get("/profile", auth_1.authenticateJWT, authController_1.getProfile);
router.put("/profile", auth_1.authenticateJWT, authController_1.updateProfile);
router.put("/change-password", auth_1.authenticateJWT, authController_1.changePassword);
router.put("/upgrade", auth_1.authenticateJWT, authController_1.upgradePlan);
router.delete("/delete-account", auth_1.authenticateJWT, authController_1.deleteAccount);
// Security Module Routes
router.post("/send-otp", authController_1.sendOtp);
router.post("/verify-otp-login", authController_1.verifyOtpLogin);
router.post("/register-biometric", auth_1.authenticateJWT, authController_1.registerBiometric);
router.post("/biometric-login", authController_1.biometricLogin);
router.put("/security/otp", auth_1.authenticateJWT, authController_1.toggleOtpSetting);
router.put("/security/biometrics", auth_1.authenticateJWT, authController_1.toggleBiometricsSetting);
router.put("/security/privacy", auth_1.authenticateJWT, authController_1.updatePrivacySettings);
router.get("/security/sessions", auth_1.authenticateJWT, authController_1.getUserSessions);
router.post("/security/logout-device", auth_1.authenticateJWT, authController_1.logoutDevice);
router.post("/security/logout-all", auth_1.authenticateJWT, authController_1.logoutAllDevices);
exports.default = router;
