"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var authRoutes_1 = require("./authRoutes");
var workerRoutes_1 = require("./workerRoutes");
var attendanceRoutes_1 = require("./attendanceRoutes");
var paymentRoutes_1 = require("./paymentRoutes");
var uploadRoutes_1 = require("./uploadRoutes");
var projectRoutes_1 = require("./projectRoutes");
var supervisorRoutes_1 = require("./supervisorRoutes");
var adminRoutes_1 = require("./adminRoutes");
var supportRoutes_1 = require("./supportRoutes");
var exportRoutes_1 = require("./exportRoutes");
var voiceRoutes_1 = require("./voiceRoutes");
var router = (0, express_1.Router)();
router.use("/auth", authRoutes_1.default);
router.use("/workers", workerRoutes_1.default);
router.use("/attendance", attendanceRoutes_1.default);
router.use("/payments", paymentRoutes_1.default);
router.use("/upload", uploadRoutes_1.default);
router.use("/projects", projectRoutes_1.default);
router.use("/supervisors", supervisorRoutes_1.default);
router.use("/admin", adminRoutes_1.default);
router.use("/support", supportRoutes_1.default);
router.use("/export", exportRoutes_1.default);
router.use("/voice", voiceRoutes_1.default);
exports.default = router;
