"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var paymentController_1 = require("../controllers/paymentController");
var auth_1 = require("../middleware/auth");
var router = (0, express_1.Router)();
router.use(auth_1.authenticateJWT);
router.get("/month", paymentController_1.getPaymentsForMonth);
router.post("/", paymentController_1.addPayment);
router.delete("/:id", paymentController_1.deletePayment);
exports.default = router;
