"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var projectController_1 = require("../controllers/projectController");
var auth_1 = require("../middleware/auth");
var subscription_1 = require("../middleware/subscription");
var router = (0, express_1.Router)();
router.use(auth_1.authenticateJWT);
router.get("/", projectController_1.getProjects);
router.post("/", (0, subscription_1.checkPlanLimit)("projects"), projectController_1.createProject);
router.put("/:id", projectController_1.updateProject);
router.delete("/:id", projectController_1.deleteProject);
exports.default = router;
