"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var supervisorController_1 = require("../controllers/supervisorController");
var auth_1 = require("../middleware/auth");
var subscription_1 = require("../middleware/subscription");
var router = (0, express_1.Router)();
router.use(auth_1.authenticateJWT);
router.get("/", supervisorController_1.getSupervisors);
router.post("/", (0, subscription_1.checkPlanLimit)("supervisors"), supervisorController_1.createSupervisor);
router.put("/:id", supervisorController_1.updateSupervisor);
router.delete("/:id", supervisorController_1.deleteSupervisor);
exports.default = router;
