"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var supportController_1 = require("../controllers/supportController");
var auth_1 = require("../middleware/auth");
var router = (0, express_1.Router)();
router.use(auth_1.authenticateJWT);
router.post("/report-problem", supportController_1.reportProblem);
router.post("/feedback", supportController_1.submitFeedback);
exports.default = router;
